Cost split
Neha/javascript-projects pull request #26
Opened 2019-10-19 16:32 UTC by Nisheanthan

-added split by percentage option 
-handled  relevant errors to display

2019-10-21 14:08 UTC, Neha requested changes
Hello,

Please look into the comments.

Thanks

2019-10-21 14:08 UTC, Neha commented on costSplit/index.html
> +      <div id="percentage-split" style="display: none">
Move the inline css from DOM to style file

2019-10-21 14:08 UTC, Neha commented on costSplit/index.html
> +          <input type='number' id="first_percentage"/>% <br/>
Either has the id namespace _fname-lname_ or _fname_lname._

2019-10-21 14:08 UTC, Neha commented on costSplit/index.html
> +      <br/>
remove <br/> and manage the styling by CSS only.

2019-10-21 19:08 UTC, Nisheanthan commented
done. Thanks for spending time to make my mistakes, I could learn many thing while involving in this project.

2019-10-22 18:05 UTC, Nisheanthan commented
thanks a lot to point out those mistakes. Nice experience working on this. Thank you

2023-02-17 19:10 UTC, Neha commented
no response. Hence, closing it

2023-02-17 19:10 UTC, closed without merging